name: Prettier Action

on:
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prettify code
        uses: creyD/prettier_action@v4.6
        with:
          prettier_options: --write **/*.{js,ts,md,vue}
          only_changed: true

      - name: 'setup git config'
        run: |
          git config --global user.name "Bot"
          git config --global user.email "username@users.noreply.github.com"
      - name: 'commit'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add . --all
          git commit --all --message "chore: prettier auto commit"
          git push
